from __future__ import annotations

from pdf_toolkit.models import OptionField, ToolDefinition
from pdf_toolkit.tools import (
    annotate_pdf,
    compare_pdf,
    compress_pdf,
    crop_pdf,
    image_to_pdf,
    merge_pdf,
    ocr_pdf,
    office_to_pdf,
    organize_pdf,
    page_numbers,
    pdf_to_jpg,
    pdf_to_excel,
    pdf_to_pdfa,
    pdf_to_powerpoint,
    pdf_to_word,
    protect_pdf,
    redact_pdf,
    remove_pages,
    repair_pdf,
    rotate_pdf,
    scan_to_pdf,
    sign_pdf,
    split_pdf,
    unlock_pdf,
    watermark,
)
from pdf_toolkit.utils.dependencies import office_renderer_status, tesseract_status


def build_registry() -> list[ToolDefinition]:
    return [
        ToolDefinition(
            "merge_pdf",
            "Organize PDF",
            "Merge PDF",
            "Combine multiple PDF files into a single document.",
            "merge",
            merge_pdf.run,
            keywords=["combine", "join", "merge"],
            workflow_steps=["Add PDF files", "Reorder your stack", "Export merged PDF"],
            workspace_mode="merge",
        ),
        ToolDefinition(
            "split_pdf",
            "Organize PDF",
            "Split PDF",
            "Extract page ranges or selected pages into a new file.",
            "split",
            split_pdf.run,
            [OptionField("pages", "Pages", placeholder="1-3, 5, 8-10")],
            False,
            keywords=["extract", "pages", "split"],
            workflow_steps=["Select a PDF", "Choose page ranges", "Create output"],
        ),
        ToolDefinition(
            "remove_pages",
            "Organize PDF",
            "Remove PDF Pages",
            "Delete selected pages from a PDF.",
            "remove",
            remove_pages.run,
            [OptionField("pages", "Pages to remove", placeholder="2, 4-6")],
            False,
            keywords=["delete", "pages", "trim"],
            workflow_steps=["Select a PDF", "Choose pages to remove", "Save cleaned PDF"],
        ),
        ToolDefinition(
            "organize_pdf",
            "Organize PDF",
            "Organize PDF",
            "Reorder and rotate pages with a drag-and-drop organizer.",
            "organize",
            organize_pdf.run,
            [OptionField("page_order", "Page order"), OptionField("rotate_pages", "Rotation map", field_type="hidden")],
            False,
            keywords=["reorder", "rotate", "arrange"],
            workflow_steps=["Choose a PDF", "Arrange and rotate pages", "Save reorganized PDF"],
            workspace_mode="organize",
        ),
        ToolDefinition(
            "scan_to_pdf",
            "Organize PDF",
            "Scan to PDF",
            "Import images now and extend to scanners later.",
            "scan",
            scan_to_pdf.run,
            badge="Batch",
            keywords=["scan", "images", "camera"],
            workflow_steps=["Add image files", "Review file order", "Create PDF"],
        ),
        ToolDefinition(
            "compress_pdf",
            "Optimize PDF",
            "Compress PDF",
            "Reduce file size with quality presets.",
            "compress",
            compress_pdf.run,
            [OptionField("preset", "Preset", "choice", "Balanced", choices=["High quality", "Balanced", "Smallest file"])],
            False,
            keywords=["optimize", "shrink", "compress"],
            workflow_steps=["Select a PDF", "Choose compression preset", "Export optimized file"],
        ),
        ToolDefinition(
            "repair_pdf",
            "Optimize PDF",
            "Repair PDF",
            "Attempt to salvage and rewrite a damaged PDF.",
            "repair",
            repair_pdf.run,
            [],
            False,
            keywords=["repair", "fix", "recover"],
            workflow_steps=["Select a PDF", "Review repair target", "Write repaired copy"],
        ),
        ToolDefinition(
            "ocr_pdf",
            "Optimize PDF",
            "OCR PDF",
            "Make scanned PDFs searchable with local Tesseract OCR.",
            "ocr",
            ocr_pdf.run,
            [],
            False,
            False,
            False,
            True,
            tesseract_status,
            keywords=["ocr", "searchable", "scan"],
            workflow_steps=["Select a scanned PDF", "Confirm OCR settings", "Run local OCR"],
            badge="Dependency",
        ),
        ToolDefinition(
            "image_to_pdf",
            "Convert to PDF",
            "Image to PDF",
            "Create PDFs from JPG, PNG, or BMP files.",
            "image",
            image_to_pdf.run,
            badge="Batch",
            keywords=["images", "jpg", "png"],
            workflow_steps=["Add images", "Arrange order", "Export PDF"],
        ),
        ToolDefinition(
            "office_to_pdf",
            "Convert to PDF",
            "Word/PowerPoint/Excel to PDF",
            "Convert modern Office files into PDF locally. Uses bundled LibreOffice automatically for higher fidelity when available.",
            "office",
            office_to_pdf.run,
            [
                OptionField(
                    "source_type",
                    "Source type",
                    "choice",
                    "Word",
                    choices=["Word", "PowerPoint", "Excel"],
                )
            ],
            False,
            True,
            False,
            True,
            office_renderer_status,
            ["docx to pdf", "pptx to pdf", "xlsx to pdf", "office to pdf", "libreoffice", "bundled renderer"],
            ["Choose an Office file", "Confirm output folder", "Run Office to PDF conversion"],
            "Built-in",
        ),
        ToolDefinition(
            "pdf_to_jpg",
            "Convert from PDF",
            "PDF to JPG",
            "Export each PDF page as a JPG image.",
            "export",
            pdf_to_jpg.run,
            [OptionField("dpi", "DPI", default="150")],
            False,
            True,
            keywords=["export", "images", "jpg"],
            workflow_steps=["Select a PDF", "Set output quality", "Export images"],
            badge="Batch",
        ),
        ToolDefinition(
            "pdf_to_word",
            "Convert from PDF",
            "PDF to Word (.docx)",
            "Convert PDF content into a proper Word document with best-effort layout preservation.",
            "word",
            pdf_to_word.run,
            keywords=["word", "docx", "editable"],
            workflow_steps=["Select a PDF", "Review export target", "Create Word document"],
        ),
        ToolDefinition(
            "pdf_to_powerpoint",
            "Convert from PDF",
            "PDF to PowerPoint (.pptx)",
            "Layout-preserving slide export with one rendered PDF page per slide.",
            "powerpoint",
            pdf_to_powerpoint.run,
            keywords=["slides", "ppt", "layout"],
            workflow_steps=["Select a PDF", "Review export target", "Create PowerPoint deck"],
        ),
        ToolDefinition(
            "pdf_to_excel",
            "Convert from PDF",
            "PDF to Excel (.xlsx)",
            "Layout-preserving workbook export with one rendered PDF page per worksheet.",
            "excel",
            pdf_to_excel.run,
            keywords=["excel", "xlsx", "layout"],
            workflow_steps=["Select a PDF", "Review export target", "Create Excel workbook"],
        ),
        ToolDefinition(
            "pdf_to_pdfa",
            "Convert from PDF",
            "PDF to PDF/A",
            "Create an archival-oriented normalized PDF copy without strict compliance guarantees.",
            "archive",
            pdf_to_pdfa.run,
            keywords=["archive", "pdfa", "archival"],
            workflow_steps=["Select a PDF", "Review archival output", "Create normalized PDF"],
        ),
        ToolDefinition(
            "rotate_pdf",
            "Edit PDF",
            "Rotate PDF",
            "Rotate selected pages by 90, 180, or 270 degrees.",
            "rotate",
            rotate_pdf.run,
            [
                OptionField("pages", "Pages", placeholder="1-3"),
                OptionField("angle", "Angle", "choice", "90", choices=["90", "180", "270"]),
            ],
            False,
            keywords=["rotate", "turn", "pages"],
            workflow_steps=["Select a PDF", "Choose pages and angle", "Save rotated PDF"],
        ),
        ToolDefinition(
            "page_numbers",
            "Edit PDF",
            "Page Numbers",
            "Overlay page numbering with position settings.",
            "numbers",
            page_numbers.run,
            [
                OptionField(
                    "position",
                    "Position",
                    "choice",
                    "Bottom Right",
                    choices=["Bottom Right", "Bottom Center", "Top Right", "Top Center"],
                )
            ],
            False,
            keywords=["numbers", "pagination", "footer"],
            workflow_steps=["Select a PDF", "Choose numbering position", "Save numbered PDF"],
        ),
        ToolDefinition(
            "watermark",
            "Edit PDF",
            "Watermark",
            "Apply a text watermark across all pages.",
            "watermark",
            watermark.run,
            [OptionField("text", "Watermark text", default="CONFIDENTIAL")],
            False,
            keywords=["watermark", "stamp", "overlay"],
            workflow_steps=["Select a PDF", "Customize watermark", "Save watermarked PDF"],
        ),
        ToolDefinition(
            "annotate_pdf",
            "Edit PDF",
            "Edit PDF",
            "Add text annotation overlays to selected pages.",
            "annotate",
            annotate_pdf.run,
            [OptionField("pages", "Pages", placeholder="1-2"), OptionField("text", "Annotation text", default="Reviewed offline")],
            False,
            keywords=["annotate", "notes", "text"],
            workflow_steps=["Select a PDF", "Enter annotation details", "Save edited PDF"],
        ),
        ToolDefinition(
            "crop_pdf",
            "Edit PDF",
            "Crop PDF",
            "Trim margins with a uniform crop value.",
            "crop",
            crop_pdf.run,
            [OptionField("margin", "Margin", default="18")],
            False,
            keywords=["crop", "trim", "margins"],
            workflow_steps=["Select a PDF", "Set crop margin", "Save cropped PDF"],
        ),
        ToolDefinition(
            "unlock_pdf",
            "PDF Security",
            "Unlock PDF",
            "Remove encryption when the correct password is known.",
            "unlock",
            unlock_pdf.run,
            [OptionField("password", "Password", field_type="password")],
            False,
            keywords=["unlock", "decrypt", "password"],
            workflow_steps=["Select a PDF", "Enter password", "Save unlocked PDF"],
        ),
        ToolDefinition(
            "protect_pdf",
            "PDF Security",
            "Protect PDF",
            "Add password encryption to a PDF.",
            "protect",
            protect_pdf.run,
            [OptionField("password", "Password", field_type="password", required=True)],
            False,
            keywords=["protect", "encrypt", "password"],
            workflow_steps=["Select a PDF", "Set protection password", "Save protected PDF"],
        ),
        ToolDefinition(
            "sign_pdf",
            "PDF Security",
            "Sign PDF",
            "Stamp an image signature into the final page.",
            "sign",
            sign_pdf.run,
            [OptionField("signature_image", "Signature image", field_type="file")],
            False,
            keywords=["sign", "signature", "stamp"],
            workflow_steps=["Select a PDF", "Choose signature image", "Save signed PDF"],
        ),
        ToolDefinition(
            "compare_pdf",
            "PDF Security",
            "Compare PDF",
            "Generate a local text-diff report for two PDFs.",
            "compare",
            compare_pdf.run,
            keywords=["compare", "diff", "report"],
            workflow_steps=["Choose two PDFs", "Review source order", "Generate comparison report"],
        ),
        ToolDefinition(
            "redact_pdf",
            "PDF Security",
            "Redact PDF",
            "Permanently redact matching text content.",
            "redact",
            redact_pdf.run,
            [OptionField("text", "Text to redact", required=True)],
            False,
            keywords=["redact", "remove text", "privacy"],
            workflow_steps=["Select a PDF", "Enter redaction target", "Save redacted PDF"],
        ),
    ]
